function networks = define_network_mappings()
    % Define the 8 networks (7 Yeo + Subcortical)
    networks = struct();
    networks.VIS = struct('name', 'Visual Network', ...
                         'rois', [1:9, 59:66]);
    networks.SMN = struct('name', 'Somatomotor Network', ...
                         'rois', [10:15, 67:74]);
    networks.DAN = struct('name', 'Dorsal Attention Network', ...
                         'rois', [16:23, 75:81]);
    networks.VAN = struct('name', 'Ventral Attention Network', ...
                         'rois', [24:30, 82:86]);
    networks.LIM = struct('name', 'Limbic Network', ...
                         'rois', [31:33, 87:88]);
    networks.FPN = struct('name', 'Frontoparietal Network', ...
                         'rois', [34:37, 89:97]);
    networks.DMN = struct('name', 'Default Mode Network', ...
                         'rois', [38:50, 98:108]);
    networks.SUB = struct('name', 'Subcortical Regions', ...
                         'rois', [51:58, 109:116]);
end